import Link from 'next/link';

// import './globals.css';
import styles from './layout.module.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={styles.body}>
      <nav >
        <ul className ={styles.nav}>
          <Link href="/">
          <li className={styles.li}>Home</li>
          </Link>
          <Link href="/pages/attraction">
      <li className={styles.li}>Find an Attraction</li>
      </Link>
        <Link href="/register">
      <li className={styles.li}>Register</li>
      </Link>
          <Link href="/login">
      <li className={styles.li}>Login</li>
      </Link>
      </ul>
      </nav>
      {children}
      </body>
    </html>
  )
}
